default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: devhub_development

test:
  <<: *default
  database: devhub_test

production:
  <<: *default
  database: devhub_production
  username: devhub
  password: <%= ENV['DEVHUB_DATABASE_PASSWORD'] %>
